# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edetail',
            name='event',
        ),
        migrations.DeleteModel(
            name='Edetail',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
